a=input("โปรดกรอกชื่อ ")
print (a)
b=input("โปรดกรอกอายุ ")
print (b)
c=input("โปรดกรอกรหัสนักศึกษา ")
print (c)
d=input("โปรดกรอกชั้นปี ")
print (d)
e=input("โปรดกรอกชื่อเล่น ")
print (e)
f=float(input("โปรดกรอกส่วนสูง "))
print (f)
l=float(input("โปรดกรอกน้ำหน้ก "))
A = f+l
print (l)
print ("ประวัติย่อ")
print(f"ชื่อ : {a} อายุ {b} ปี" )
print(f"รหัสนักศึกษา :{c} ชั้นปี : {d}")
print(f"ชื่อเล่น : {e}")
print(f"ส่วนสูง : {f} เซนติเมตร น้ำหน้ก : {l} กิโลกรัม")
print(f"ส่วนสูง + น้ำหน้ก = {A}" )